version: '3.9'

services:
  # web:
  #   # build: 
  #   #   dockerfile: Dockerfile
  #   #   context: .
  #   container_name: web
  #   image: dockf
  #   depends_on:
  #     - postgress
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=12345678
  #     - POSTGRES_DB=slotmachine
  #     - POSTGRES_HOST=postgress
  #     - POSTGRES_PORT=5432 
  #     # DATABASE_URL: postgres://postgres:12345678@postgres:5432/slotmachine
  #   # expose: 
  #   #     - 8000
  #   ports:
  #     - "8000:8000"
  #   command: python main.py

  postgress:
    container_name: postgress
    image: postgres:16.4
    environment:
      POSTGRES_DB: slotmachine
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    # command: psql -U postgress && 12345678


volumes:
  postgres_data:
